services:
  front:
    image: aleygues/wns0924-tgc-frontend
    # override default CMD command for the frontend
    entrypoint: sh
    command: -c "npx vite --host"
  back:
    image: aleygues/wns0924-tgc-backend
    env_file:
      - database.env
      - backend.env
  db:
    image: postgres
    ports:
      - 4001:5432
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
    - 4000:80
    depends_on:
    - back
    - front

volumes:
  dbdata:
    driver: local