GET http://127.0.0.1:5000/ads

###

POST http://127.0.0.1:5000/ads
Content-Type: application/json

{
  "title": "Bike to sell",
  "description": "My bike is blue, working fine. I'm selling it because I've got a new one",
  "owner": "aurelien.leygues@gmail.com",
  "price": 99,
  "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
  "location": "Villeurbanne",
  "createdAt": "2023-09-05T10:13:14.755Z"
}