GET http://127.0.0.1:5000/ads

###

POST http://127.0.0.1:5000/ads
Content-Type: application/json

{
  "title": "Super beau vélo de route",
  "description": "It's a red bike",
  "owner": "aurelien@aleygues.fr",
  "price": 10000,
  "picture": "https://cdn.pixabay.com/photo/2020/03/23/11/19/bike-4960516_1280.jpg",
  "location": "Villeurbanne",
  "category": { "id": 1 },
  "tags": [{ "id": 1 }]
}

###

PATCH http://127.0.0.1:5000/ads/1
Content-Type: application/json

{
  "title": "Red bike",
  "description": "This is a super bike!",
  "price": 200
}

###

PUT http://127.0.0.1:5000/ads/11
Content-Type: application/json

{
  "title": "Super beau vélo de route",
  "description": "It's a red bike",
  "owner": "aurelien@aleygues.fr",
  "price": 10000,
  "picture": "https://cdn.pixabay.com/photo/2020/03/23/11/19/bike-4960516_1280.jpg",
  "location": "",
  "category": null,
  "tags": []
}

###

DELETE http://127.0.0.1:5000/ads/1