GET http://127.0.0.1:5000/categories

###

GET http://127.0.0.1:5000/categories/1

###

POST http://127.0.0.1:5000/categories
Content-Type: application/json

{
  "name": "Vélos de route"
}

###

PUT http://127.0.0.1:5000/categories/5
Content-Type: application/json

{
  "name": "Vêtements d'occasion"
}

###

DELETE http://127.0.0.1:5000/categories/3