name: main

on:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backendChanges: ${{ steps.filter.outputs.backendChanges }}
      frontendChanges: ${{ steps.filter.outputs.frontendChanges }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backendChanges:
              - 'backend/**'
            frontendChanges:
              - 'frontend/**'
  test-backend:
    needs: changes
    if: needs.changes.outputs.backendChanges == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: cd backend && npm ci
      - name: Run test
        run: cd backend && npm test
  test-frontend:
    needs: changes
    if: needs.changes.outputs.frontendChanges == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: cd frontend && npm ci
      - name: Run test
        run: cd frontend && npm test
