name: main

on:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backendChanges: ${{ steps.filter.outputs.backendChanges }}
      frontendChanges: ${{ steps.filter.outputs.frontendChanges }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backendChanges:
              - 'backend/**'
            frontendChanges:
              - 'frontend/**'
  test-backend:
    needs: changes
    if: needs.changes.outputs.backendChanges == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: cd backend && npm ci
      - name: Run test
        run: cd backend && npm test
  test-frontend:
    needs: changes
    if: needs.changes.outputs.frontendChanges == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: cd frontend && npm ci
      - name: Run test
        run: cd frontend && npm test
  build-frontend:
    needs: changes
    if: needs.changes.outputs.frontendChanges == 'true' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          tags: ${{ vars.DOCKERHUB_FRONTEND_REPO }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build-backend:
    needs: changes
    if: needs.changes.outputs.backendChanges == 'true' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: ${{ vars.DOCKERHUB_BACKEND_REPO }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
